name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 패키지 설치
        run: npm install

#      - name: 린트 확인
#        run: npm run lint

      - name: 빌드 확인
        run: npm run build